/*
 * This source file was generated by the Gradle 'init' task
 */
package org.game

class TicTacToeGame {
    fun printCanvas(
        canvas: List<List<Char>> = listOf(listOf(' ', ' ', ' '), listOf(' ', ' ', ' '), listOf(' ', ' ', ' '))
    ) {
        println(
            """
┌-----------┐
| ${canvas[0][0]} | ${canvas[0][1]} | ${canvas[0][2]} |
├-----------┤
| ${canvas[1][0]} | ${canvas[1][1]} | ${canvas[1][2]} |
├-----------┤
| ${canvas[2][0]} | ${canvas[2][1]} | ${canvas[2][2]} |
└-----------┘
"""
        )
    }
}

fun main() {
    var match = TicTacToeGame()
    match.printCanvas()
}
